version: '3.8'

services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_moodle
    networks:
      - moodle-network
    volumes:
      - mariadb_data:/bitnami/mariadb

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bitnami
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin123
      - MOODLE_EMAIL=admin@example.com
    depends_on:
      - mariadb
    networks:
      - moodle-network
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata

networks:
  moodle-network:

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:
